### ISSUE TITLE
Resultats de recherche : ca sautille quand on passe la souris sur la ligne

### ISSUE THREAD

**Issue by TomGallon** [KleeGroup/focus4#59]
Le problème est du a l'affichage des actions secondaires.
Au passage de la souris, le bouton s'affiche et la div (non visible) du panel des actions s'affiche sur la droite des actions --> ca dépasse et une scroll bar horizontale apparait, ce qui  fait sautiller l'écran.

pour palier à ca, j'ai posé un 
```css
#app [data-focus="results"] {
    overflow: hidden;
    padding-bottom: 200px;
}
```
pas très joli mais efficace.
D'ailleurs le data-focus est un petit reliquat ? ;)
